# fly.toml app configuration file generated for snapshare-api on 2023-11-24T11:00:30+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "snapshare-api"
primary_region = "waw"

[build]

[env]
  ALGORITHM = "***************"
  CLOUDINARY_API_KEY = "***************"
  CLOUDINARY_API_SECRET = "***************"
  CLOUDINARY_NAME = "***************"
  MAIL_FROM = "***************"
  MAIL_PASSWORD = "***************"
  MAIL_PORT = "***************"
  MAIL_SERVER = "***************"
  MAIL_USERNAME = "***************"
  POSTGRES_DB = "***************"
  POSTGRES_HOST = "***************"
  POSTGRES_PASSWORD = "***************"
  POSTGRES_USER = "***************"
  REDIS_HOST = "***************"
  REDIS_PORT = "***************"
  REDIS_PASSWORD = "***************"
  SECRET_KEY = "***************"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
