# fly.toml app configuration file generated for snapshare-api on 2023-11-24T11:00:30+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "snapshare-api"
primary_region = "waw"

[build]

[env]
  ALGORITHM = "HS256"
  CLOUDINARY_API_KEY = "732751947885972"
  CLOUDINARY_API_SECRET = "knruuAeDfjNgVAHDytDT8DcxBXA"
  CLOUDINARY_NAME = "dyltcsbtk"
  MAIL_FROM = "contacts.test.app@meta.ua"
  MAIL_PASSWORD = "teamproject@567234"
  MAIL_PORT = "465"
  MAIL_SERVER = "smtp.meta.ua"
  MAIL_USERNAME = "contacts.test.app@meta.ua"
  POSTGRES_DB = "pvfmhlra"
  POSTGRES_HOST = "cornelius.db.elephantsql.com"
  POSTGRES_PASSWORD = "zLSqxdu172Ov6uuEup1MvC7iKWkrXJue"
  POSTGRES_USER = "pvfmhlra"
  REDIS_HOST = "195.201.150.230"
  REDIS_PORT = "6379"
  REDIS_PASSWORD = "567234"
  SECRET_KEY = "secret_key"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
