"""Instead back_populates of backref

Revision ID: 68ea8d97ed1b
Revises: bf90276d11f8
Create Date: 2023-11-17 22:25:24.724414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68ea8d97ed1b'
down_revision: Union[str, None] = 'bf90276d11f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
