"""Update releationships

Revision ID: 7525bfd0b2a5
Revises: e34fe21f956c
Create Date: 2023-11-18 22:41:30.788234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7525bfd0b2a5'
down_revision: Union[str, None] = 'e34fe21f956c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
