<<<<<<<< HEAD:migrations/versions/8836361e6c9d_added_releationships.py
"""Added releationships

Revision ID: 8836361e6c9d
Revises: 78c40813d1a8
Create Date: 2023-11-18 21:18:45.590240
========
"""Added ban_status to User

Revision ID: 338b062e7d4c
Revises: b57b01b7efe9
Create Date: 2023-11-18 09:36:32.206498
>>>>>>>> origin/feature/auth:migrations/versions/338b062e7d4c_added_ban_status_to_user.py

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<<< HEAD:migrations/versions/8836361e6c9d_added_releationships.py
revision: str = '8836361e6c9d'
down_revision: Union[str, None] = '78c40813d1a8'
========
revision: str = '338b062e7d4c'
down_revision: Union[str, None] = 'b57b01b7efe9'
>>>>>>>> origin/feature/auth:migrations/versions/338b062e7d4c_added_ban_status_to_user.py
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ban_status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ban_status')
    # ### end Alembic commands ###
