"""Deleted uploaded column

Revision ID: 945a85783c80
Revises: ddac46760df6
Create Date: 2023-11-15 21:58:40.754901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '945a85783c80'
down_revision: Union[str, None] = 'ddac46760df6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'uploaded_images')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('uploaded_images', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
